image:
  - Visual Studio 2017

version: build-{build}

environment:
  QT_VER: 5.13.2
  MAKE_RUN_TESTS: true
  TARGET_NAME: qtautoupdater

  matrix:
    - PLATFORM: msvc2017_64
    - PLATFORM: mingw73_64
    - PLATFORM: winrt_x64_msvc2017
    - PLATFORM: msvc2017
    - PLATFORM: mingw73_32
    - PLATFORM: winrt_x86_msvc2017
    - PLATFORM: winrt_armv7_msvc2017

install:
  - git submodule update --init --recursive
  - git clone https://github.com/Skycoder42/QtModules.git .\qtmodules-travis
  - .\qtmodules-travis\ci\win\setup.bat

build_script:
  - .\ci\appveyor.bat
  - .\qtmodules-travis\ci\win\build.bat

after_build:
  - .\qtmodules-travis\ci\win\upload-prepare.bat

artifacts:
  - path: install\%TARGET_NAME%_*_%QT_VER%.zip

deploy:
  provider: GitHub
  auth_token:
    secure: Cp5GRQku2ZWnKPE12NB5q11ZO0Fr5mlzdUTjnLpYJr/dki4LPVqm231edFggogy8
  artifact: /.*\.zip/
  force_update: false
  on:
    appveyor_repo_tag: true

cache:
  - 'C:\Users\appveyor\AppData\Local\qdep\qdep\Cache -> appveyor.yml'
